// apps/web-stylex/src/components/interaction/interaction-timeline.tsx
import { Button, Skeleton, TapuyMark, cn } from "@interviews-tool/web-ui";
import { useTranslations } from "@interviews-tool/i18n";
import { useInteractions } from "@/hooks/use-interactions";
import { InteractionCard } from "./interaction-card";
import { INTERACTION_CONTENT_ID } from "./interaction-form";
import type { Interaction } from "@/hooks/use-interactions";

interface InteractionTimelineProps {
  hiringProcessId: string;
  onEdit?: (interaction: Interaction) => void;
  onDelete?: (interaction: Interaction) => void;
}

/* Only `offer` and `rejection` nodes carry color; every other node is muted. */
function nodeColor(type: Interaction["type"]) {
  if (type === "offer") return "bg-fuchsia";
  if (type === "rejection") return "bg-status-rejected-bg";
  return "bg-text-muted";
}

function TimelineShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative pl-8">
      <div className="absolute bottom-2 left-[7px] top-2 w-px bg-border-strong" />
      {children}
    </div>
  );
}

export function InteractionTimeline({
  hiringProcessId,
  onEdit,
  onDelete,
}: InteractionTimelineProps) {
  const t = useTranslations("interaction");
  const { data, isLoading, error } = useInteractions(hiringProcessId);

  if (isLoading) {
    return (
      <TimelineShell>
        {Array.from({ length: 3 }).map((_, index) => (
          <article key={index} className="relative mb-5">
            <div className="absolute -left-[28px] top-4 size-2 rounded-full bg-surface-2" />
            <div className="rounded-xl border border-border bg-surface px-5 py-[18px]">
              <div className="mb-3 flex items-center gap-2.5">
                <Skeleton className="h-[22px] w-16 bg-surface-2" />
                <Skeleton className="h-3 w-36 bg-surface-2" />
              </div>
              <Skeleton className="mb-2 h-4 w-48 bg-surface-2" />
              <Skeleton className="h-16 w-full bg-surface-2" />
            </div>
          </article>
        ))}
      </TimelineShell>
    );
  }

  if (error) {
    return <p className="py-12 text-center text-sm text-danger">{t("loadError")}</p>;
  }

  const interactions = [...(data?.data ?? [])].sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
  );

  if (interactions.length === 0) {
    return (
      <div className="flex flex-col items-center rounded-xl border border-border px-8 py-[88px] text-center">
        <TapuyMark className="size-9 text-text-muted" />
        <h3 className="mt-5 text-base font-medium text-text">{t("emptyTitle")}</h3>
        <p className="mt-1.5 text-sm text-text-secondary">{t("emptyBody")}</p>
        <Button
          type="button"
          variant="secondary"
          className="mt-6"
          onClick={() => {
            const textarea = document.getElementById(INTERACTION_CONTENT_ID);
            textarea?.scrollIntoView({ behavior: "smooth", block: "center" });
            textarea?.focus({ preventScroll: true });
          }}
        >
          {t("emptyCta")}
        </Button>
      </div>
    );
  }

  return (
    <TimelineShell>
      {interactions.map((interaction) => (
        <article key={interaction.id} className="relative mb-5">
          <div
            className={cn(
              "absolute -left-[28px] top-4 size-2 rounded-full",
              nodeColor(interaction.type),
            )}
          />
          <InteractionCard interaction={interaction} onEdit={onEdit} onDelete={onDelete} />
        </article>
      ))}
    </TimelineShell>
  );
}

// apps/angular-web/src/app/features/hiring-processes/detail/interactions/interaction-timeline.ts
import { Component, computed, input, output } from "@angular/core";
import type { Interaction } from "../../../../core/api/interaction.model";
import { EmptyState } from "../../../../shared/ui/empty-state";
import { injectInteractionList } from "../../interaction.queries";
import { InteractionCard } from "./interaction-card";

/* Only `offer` and `rejection` nodes carry colour; every other node is muted —
   the same rule the React timeline uses. */
function nodeClass(type: Interaction["type"]): string {
  if (type === "offer") return "bg-fuchsia";
  if (type === "rejection") return "bg-status-rejected-bg";
  return "bg-text-muted";
}

@Component({
  selector: "app-interaction-timeline",
  imports: [InteractionCard, EmptyState],
  template: `
    @if (query.isPending()) {
      <div class="relative pl-8">
        <div class="absolute bottom-2 left-[7px] top-2 w-px bg-border-strong"></div>
        @for (row of skeletonRows; track row) {
          <article class="relative mb-5">
            <div class="absolute -left-[28px] top-4 size-2 rounded-full bg-surface-2"></div>
            <div class="rounded-xl border border-border bg-surface px-5 py-[18px]">
              <div class="mb-3 flex items-center gap-2.5">
                <div class="h-[22px] w-16 animate-pulse rounded bg-surface-2"></div>
                <div class="h-3 w-36 animate-pulse rounded bg-surface-2"></div>
              </div>
              <div class="mb-2 h-4 w-48 animate-pulse rounded bg-surface-2"></div>
              <div class="h-16 w-full animate-pulse rounded bg-surface-2"></div>
            </div>
          </article>
        }
      </div>
    } @else if (query.isError()) {
      <app-empty-state title="Could not load interactions" [message]="query.error().message">
        <button type="button" class="btn btn-secondary" (click)="query.refetch()">Retry</button>
      </app-empty-state>
    } @else if (interactions().length === 0) {
      <app-empty-state
        title="No interactions logged yet"
        message="Log what just happened and it will show up here."
      />
    } @else {
      <div class="relative pl-8">
        <div class="absolute bottom-2 left-[7px] top-2 w-px bg-border-strong"></div>
        @for (interaction of interactions(); track interaction.id) {
          <article class="relative mb-5">
            <div
              class="absolute -left-[28px] top-4 size-2 rounded-full"
              [class]="nodeClass(interaction.type)"
            ></div>
            <app-interaction-card
              [interaction]="interaction"
              (edit)="edit.emit($event)"
              (remove)="remove.emit($event)"
            />
          </article>
        }
      </div>
    }
  `,
})
export class InteractionTimeline {
  readonly hiringProcessId = input.required<string>();
  readonly edit = output<Interaction>();
  readonly remove = output<Interaction>();

  protected readonly skeletonRows = [0, 1, 2];
  protected readonly nodeClass = nodeClass;

  protected readonly query = injectInteractionList(() => this.hiringProcessId());

  /* Newest first. The API returns insertion order, and the timeline reads
     top-down as "most recent thing that happened". */
  protected readonly interactions = computed(() =>
    [...(this.query.data() ?? [])].sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    ),
  );
}
