// apps/web-stylex/src/components/interaction/interaction-card.tsx
import { Button, MarkdownContent } from "@interviews-tool/web-ui";
import { useFormatter } from "@interviews-tool/i18n";
import { Pencil, Trash2 } from "lucide-react";
import { InteractionTypeBadge } from "./interaction-type-badge";
import type { Interaction } from "@/hooks/use-interactions";

interface InteractionCardProps {
  interaction: Interaction;
  onEdit?: (interaction: Interaction) => void;
  onDelete?: (interaction: Interaction) => void;
}

/* Content renders in full — the timeline is the product, not a teaser. */
export function InteractionCard({
  interaction,
  onEdit,
  onDelete,
}: InteractionCardProps): React.ReactElement {
  const format = useFormatter();
  const createdAt = new Date(interaction.createdAt);

  return (
    <div className="rounded-xl border border-border bg-surface px-5 py-[18px]">
      <div className="mb-2 flex items-center justify-between gap-2">
        <div className="flex flex-wrap items-center gap-2.5">
          <InteractionTypeBadge type={interaction.type} />
          <span className="mono text-xs text-text-muted">
            {format.dateTime(createdAt, { month: "short", day: "numeric", year: "numeric" })} ·{" "}
            {format.dateTime(createdAt, { hour: "numeric", minute: "2-digit" })}
          </span>
        </div>
        <div className="flex shrink-0 gap-0.5">
          {onEdit && (
            <Button
              variant="ghost"
              size="icon-xs"
              className="size-[26px] text-text-muted hover:text-text"
              onClick={() => onEdit(interaction)}
            >
              <Pencil className="size-3" />
            </Button>
          )}
          {onDelete && (
            <Button
              variant="ghost"
              size="icon-xs"
              className="size-[26px] text-text-muted hover:text-text"
              onClick={() => onDelete(interaction)}
            >
              <Trash2 className="size-3" />
            </Button>
          )}
        </div>
      </div>

      {interaction.title && (
        <h4 className="mb-2.5 text-sm font-medium text-text">{interaction.title}</h4>
      )}

      <MarkdownContent content={interaction.content} />
    </div>
  );
}

// apps/angular-web/src/app/features/hiring-processes/detail/interactions/interaction-card.ts
import { Component, input, output } from "@angular/core";
import type { Interaction } from "../../../../core/api/interaction.model";
import { AbsoluteDatePipe } from "../../../../shared/pipes/absolute-date.pipe";
import { MarkdownContent } from "../../../../shared/ui/markdown-content";
import { InteractionTypeBadge } from "./interaction-type-badge";

/* Content renders in full — the timeline is the product, not a teaser. */
@Component({
  selector: "app-interaction-card",
  imports: [InteractionTypeBadge, MarkdownContent, AbsoluteDatePipe],
  template: `
    <div class="rounded-xl border border-border bg-surface px-5 py-[18px]">
      <div class="mb-2 flex items-center justify-between gap-2">
        <div class="flex flex-wrap items-center gap-2.5">
          <app-interaction-type-badge [type]="interaction().type" />
          <span class="font-mono text-xs text-text-muted">
            {{ interaction().createdAt | absoluteDate }}
          </span>
        </div>
        <div class="flex shrink-0 gap-0.5">
          <button
            type="button"
            class="btn-icon"
            aria-label="Edit interaction"
            (click)="edit.emit(interaction())"
          >
            ✎
          </button>
          <button
            type="button"
            class="btn-icon"
            aria-label="Delete interaction"
            (click)="remove.emit(interaction())"
          >
            🗑
          </button>
        </div>
      </div>

      @if (interaction().title; as title) {
        <h4 class="mb-2.5 text-sm font-medium text-text">{{ title }}</h4>
      }

      <app-markdown [content]="interaction().content" />
    </div>
  `,
})
export class InteractionCard {
  readonly interaction = input.required<Interaction>();
  readonly edit = output<Interaction>();
  readonly remove = output<Interaction>();
}
